# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aa36393775b18557ce5f250298a594ce31168d73c93b790f4378df35846e40aa02f9c594fc9c55386f5af1be41688c513db45d850533864a95e3950cc2c517d

test:
  secret_key_base: 26698dac395a4dc6aa7f875d6fa6098e84f136b0c93b566c13bcda8768cbbdf01172ddd43d5a4470f7e55c325afbcb32b296f572fde516db44a308574de68359

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
